// data.js - Justin Hatch portfolio content

window.JH_DATA = {
  name: 'Justin Hatch',
  role: 'AI / ML Engineer',
  location: 'Eugene, Oregon · Remote',
  domain: 'justinhatch.com',
  graduating: 'June 2026',
  school: 'University of Oregon',
  degree: 'B.S. Computer Science',
  honors: ['Dean\'s List', 'Department Honors', 'Quack Hacks II - Winner', 'ETH Global Hackathon - Top 10% of 470+ projects'],

  links: {
    github:    { label: 'github.com/jhatch3',           href: 'https://github.com/jhatch3' },
    linkedin:  { label: 'linkedin.com/in/justinhatch',  href: 'https://www.linkedin.com/in/justinhatch/' },
    twitter:   { label: 'x.com/jjhatch11',              href: 'https://x.com/jjhatch11' },
    instagram: { label: '@justinhatch',                 href: '#' },
    email:     { label: 'jjhatch03@gmail.com',          href: 'mailto:jjhatch03@gmail.com' },
    resume:    { label: 'resume.pdf',                   href: 'Resume.pdf' },
  },

  about: [
    "Generalist AI/ML engineer focused on LLMs, agents, and RAG. I build systems that ship - production sales agents, cohort analytics, supply-chain provenance.",
    "Currently AI Engineering Intern at Modern Amenities and Lead Software Engineer at Oregon Blockchain Group. Graduating June 2026 from the University of Oregon.",
  ],

  experience: [
    {
      company: 'Modern Amenities',
      role:    'AI Engineering Intern - AIMS',
      type:    'Internship',
      where:   'Coburg, Oregon',
      start:   'Mar 2026',
      end:     'Present',
      bullets: [
        'Built Claude + FastAPI sales chatbot qualifying prospects across dozens of machines in a 3D/AR demo.',
        'Used tool-use API to emit structured calls so the frontend renders deterministic CTAs.',
        'Red-teamed system prompt against 5 jailbreak vectors - all rejected via a single canonical refusal.',
        'Cut inference cost via prompt caching; added rate limit, 24h token budget, and structured logs with request IDs and cached-token counts.',
      ],
      tags: ['Claude', 'FastAPI', 'Tool Use', 'Prompt Caching', 'RAG'],
    },
    {
      company: 'Oregon Blockchain Group',
      role:    'Lead Software Engineer',
      type:    'Promoted from Software Developer · Dec 2025',
      where:   'University of Oregon · Eugene',
      start:   'Oct 2025',
      end:     'Present',
      bullets: [
        'Lead 2 projects: Crop Share (supply-chain provenance, farm → retailer) and Trial Weave (GLP-1 tracking with cohort RWE analytics).',
        'Translate stakeholder needs into scopes, acceptance criteria, and implementation plans.',
        'Sit on the recruitment board, pitch in core CS classes, interview engineering candidates.',
        'Grew the group >30% in under a year.',
      ],
      tags: ['Leadership', 'Rust', 'Postgres', 'Recruitment'],
    },
    {
      company: 'Oregon Software Consulting',
      role:    'Jr Software Developer',
      type:    'Freelance',
      where:   'Eugene, Oregon',
      start:   'Oct 2025',
      end:     'Jan 2026',
      bullets: [
        'Client-facing software engineering across data + AI scopes.',
      ],
      tags: ['Python', 'Data', 'AI'],
    },
    {
      company: 'University of Oregon',
      role:    'Student Business Operations Assistant',
      type:    'Part-time',
      where:   'Eugene, Oregon',
      start:   'Oct 2023',
      end:     'Present',
      bullets: [
        'Built a Power Automate + LLM automation system that files online invoices and statements.',
        'Reduced manual processing time by ~100%.',
      ],
      tags: ['Power Automate', 'Excel', 'Power BI'],
    },
  ],

  projects: [
    { id: 'sales-agent', name: 'Sales Agent', subtitle: 'Modern Amenities · 2026',
      tags: ['AI Agents','LLM','Tool Use','Backend'], status: 'shipped',
      bullets: [
        'Built Claude + FastAPI sales chatbot qualifying prospects across dozens of machines in a 3D/AR demo.',
        'Anthropic tool-use API emits structured calls so the frontend renders deterministic CTAs (no free-text parsing).',
        'Red-teamed system prompt against 5 jailbreak vectors - all rejected via a single canonical refusal.',
        'Cut inference cost via prompt caching; added per-IP rate limiting, 24h token budget, and structured logs with cached-token counts.',
      ],
    },
    { id: 'justin-portfolio', name: 'This Portfolio', subtitle: 'macOS desktop simulation with a live AI bot and agent skills',
      tags: ['Frontend','AI Agents','LLM','Full-Stack'], status: 'shipped', url: 'https://github.com/jhatch3/justin-portfolio',
      bullets: [
        'macOS desktop sim with draggable, resizable windows, dock magnification, and ⌘K spotlight.',
        'Streaming Claude chatbot - prompt caching, sliding 24h rate limit, SSE token deltas, hardened against 12+ prompt-injection vectors.',
        'Custom agent skills (/projects, /experience, /now) - I can add any GitHub repo to the site as a project, experience, or writing entry with one slash command.',
        'Live data widgets - Coinbase WebSocket order book, real Yahoo Finance stock ticker via server proxy.',
        'iOS home-screen layout for phones; full macOS for desktop. Same React tree, branched at the root.',
      ],
    },
    { id: 'lethe', name: 'Lethe', subtitle: 'Decentralized AI consensus that audits medical bills',
      tags: ['AI Agents','Blockchain','Healthcare','Python'], status: 'in-progress', url: 'https://github.com/jhatch3/lethe-',
      bullets: [
        'Decentralized AI consensus system that audits medical bills and disputes overcharges.',
        'Multi-agent verification across independent reviewers for tamper resistance.',
        'Privacy-preserving by design - never stores patient records.',
      ],
    },
    { id: 'evergreen-capital', name: 'Evergreen Capital', subtitle: 'AI-governed prediction fund trading Polymarket',
      tags: ['AI Agents','Blockchain','TypeScript'], status: 'in-progress', url: 'https://github.com/jhatch3/Evergreen-Capital',
      bullets: [
        'Decentralized, AI-governed prediction fund autonomously trading on Polymarket.',
        'Strategies generated by Google Gemini and executed via on-chain transactions.',
        'TypeScript core; pluggable strategy modules.',
      ],
    },
    { id: 'trial-weave', name: 'Trial Weave', subtitle: 'OBG · GLP-1 RWE analytics',
      tags: ['Machine Learning','Healthcare','Python'], status: 'in-progress',
      bullets: [
        'GLP-1 drug tracking with cohort Real-World Evidence (RWE) analytics.',
        'Lead engineering at Oregon Blockchain Group across 4 contributors.',
        'Translate stakeholder needs into scopes, acceptance criteria, and implementation plans.',
      ],
    },
    { id: 'retention-flow', name: 'Retention Flow', subtitle: 'Production-grade customer churn prediction platform',
      tags: ['Machine Learning','MLOps','Python'], status: 'shipped', url: 'https://github.com/jhatch3/retention-flow',
      bullets: [
        'End-to-end churn prediction: ingestion, feature pipelines, model training, model serving.',
        'Reproducible MLOps - tracked experiments, versioned data, deployable model artifacts.',
        'Python + scikit-learn / XGBoost stack with proper cross-validation and holdout eval.',
      ],
    },
    { id: 'invoice-bot', name: 'Invoice Automation', subtitle: 'U of O · Power Automate + LLM',
      tags: ['Automation','LLM'], status: 'shipped',
      bullets: [
        'Power Automate + LLM automation that files online invoices and statements.',
        'Reduced manual processing time by ~100% (eliminated the task entirely).',
        'Built at U of O Student Business Operations.',
      ],
    },
    { id: 'ml-churn-report', name: 'ML Churn Report', subtitle: 'Final project · CS472 / 572 (Machine Learning)',
      tags: ['Machine Learning','Coursework','Python'], status: 'shipped', url: 'https://github.com/jhatch3/ML-Churn_Report',
      bullets: [
        'Final project for CS472 / 572 - applied multiple classifiers to a customer churn dataset.',
        'Compared logistic regression, random forest, and gradient-boosted models on cross-validated metrics.',
        'Documented feature engineering, evaluation, and model selection process.',
      ],
    },
    { id: 'crop-share', name: 'Crop Share', subtitle: 'OBG · supply-chain provenance',
      tags: ['Blockchain','Backend','Rust'], status: 'in-progress',
      bullets: [
        'On-chain supply-chain provenance: track produce from farm through retailer.',
        'Rust + Postgres backend with verifiable event log.',
        'Lead at Oregon Blockchain Group.',
      ],
    },
    { id: 'polymarket-live', name: 'Polymarket Live', subtitle: 'CLI streaming BTC 5-min market order books via WS',
      tags: ['Data Pipeline','Blockchain','Python'], status: 'shipped', url: 'https://github.com/jhatch3/polymarket-live',
      bullets: [
        'CLI that fetches Polymarket CLOB token IDs for BTC 5-minute Up/Down markets.',
        'Streams the live order books over WebSocket for downstream analytics.',
        'Python implementation, useful as a building block for prediction-market strategies.',
      ],
    },
    { id: 'link-dashboard', name: 'LINK Dashboard', subtitle: 'Dune dashboard for $LINK · Penn Blockchain',
      tags: ['Blockchain','Data Analysis','SQL'], status: 'shipped', url: 'https://github.com/jhatch3/LINK-dashboard',
      bullets: [
        'Dune Analytics dashboard for the $LINK token in collaboration with Penn Blockchain.',
        'SQL queries on on-chain data; visualizations of supply, holders, and flows.',
      ],
    },
    { id: 'stock-pipeline', name: 'Stock Pipeline', subtitle: 'Data pipeline for stock analysis',
      tags: ['Data Pipeline','JavaScript','Finance'], status: 'shipped', url: 'https://github.com/jhatch3/stock-pipe-line',
      bullets: [
        'Data pipeline that fetches, cleans, and stores stock market data for downstream analysis.',
        'JavaScript implementation, modular fetcher / transformer / sink layers.',
      ],
    },
    { id: 'nba-salary-mining', name: 'NBA Salary Mining', subtitle: 'Predictors of player value from salary data',
      tags: ['Data Analysis','Coursework','Python'], status: 'shipped', url: 'https://github.com/jhatch3/NBA-Salary-Minning',
      bullets: [
        'Mined NBA salary data to identify predictors of player value.',
        'Exploratory analysis, correlation studies, and writeup.',
      ],
    },
  ],

  skills: {
    'AI Engineering':       ['LangChain','OpenRouter','MCP','RAG','Vector DBs','Embeddings','Tool Use','Anthropic API','OpenAI API','NLP'],
    'ML Engineering':       ['Model Eval','Cross-Validation','Hyperparameter Tuning','Deployment','Inference Opt','Experiment Tracking','Feature Pipelines','Data Versioning','MLflow'],
    'Machine Learning':     ['Feature Eng','Predictive Modeling','XGBoost','PyTorch','HF Transformers','Hypothesis Testing','A/B Testing','Statistics','EDA','Time Series'],
    'Languages':            ['Python','SQL','C / C++','TypeScript','Rust'],
    'Backend / Infra':      ['FastAPI','Redis','REST','Linux / Bash','Microservices','CI/CD','Pytest','Docker','Airflow','AWS','Postgres'],
    'Data':                 ['Pandas','NumPy','SciPy','Scikit-learn','PySpark'],
    'Frontend':             ['Next.js','React','Node.js','Streamlit'],
  },

  certs: [
    'DataCamp - Associate Data Engineer in SQL',
    'Intel - Data Visualization',
    'OpenAI - AI Professional Skills',
  ],

  writing: [
    { id: 'link-dashboard', title: '$LINK on-chain: a Dune dashboard for Penn Blockchain', date: 'Feb 2026', mins: 5, kind: 'Dashboard',     url: 'https://github.com/jhatch3/LINK-dashboard' },
    { id: 'ml-churn',       title: 'A churn classifier for retention modeling (CS472/572)', date: 'Dec 2025', mins: 7, kind: 'Course Report', url: 'https://github.com/jhatch3/ML-Churn_Report' },
    { id: 'nba-salary',     title: 'Mining NBA salary data: predictors of player value',   date: 'May 2024', mins: 6, kind: 'Course Report', url: 'https://github.com/jhatch3/NBA-Salary-Minning' },
  ],

  now: [
    { line: 'Building a sales agent at Modern Amenities.',   detail: 'Claude · FastAPI · tool-use' },
    { line: 'Leading Crop Share + Trial Weave at OBG.',      detail: '2 projects · 4 engineers' },
    { line: 'Reading: Designing Data-Intensive Applications.' },
    { line: 'Listening: lo-fi + Bonobo.' },
    { line: 'Looking for: full-time AI/ML eng roles, June 2026 start.' },
  ],
};
