#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Wizard state lives here, NOT in the app's .env (which holds the real API key
# and is consumed by the server). Re-runs resume from these values.
ENV_FILE=".deploy.env"

REPO_SSH="git@github.com:jhatch3/justin-portfolio.git"
DOMAIN="justinhatch.dev"
REMOTE_USER="ec2-user"   # Amazon Linux 2023

# ssh_run "cmd" — run a command on the instance, streaming output.
ssh_run() {
  ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new \
      -o ConnectTimeout=10 "$REMOTE_USER@$ELASTIC_IP" "$1"
}

banner "Deploy justin-portfolio to AWS ($DOMAIN)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking this machine has what the later stages need."
printf '\n'

missing=0
for c in ssh dig curl git; do
  if command -v "$c" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$c"
  else
    printf '  %s✗%s %s — install it before continuing\n' "$RED" "$RESET" "$c"; missing=1
  fi
done
(( missing )) && { warn "missing tools above; stopping."; exit 1; }

printf '\n'
if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
  warn "working tree has uncommitted changes — the instance clones from GitHub,"
  note "  so anything uncommitted will NOT be deployed."
  confirm "Continue anyway?" || exit 1
else
  say "Working tree clean."
fi

if git rev-parse @{u} >/dev/null 2>&1 && [[ -n "$(git log @{u}..HEAD --oneline 2>/dev/null)" ]]; then
  warn "you have commits not pushed to origin — push them or they won't deploy."
  confirm "Continue anyway?" || exit 1
fi

# The app's API key: reuse the local one rather than making them find it again.
printf '\n'
LOCAL_KEY=""
if [[ -f .env ]]; then
  LOCAL_KEY=$(grep -E '^ANTHROPIC_API_KEY=' .env 2>/dev/null | tail -n1 | cut -d= -f2- || true)
fi
if [[ -n "$LOCAL_KEY" ]]; then
  say "Found ANTHROPIC_API_KEY in your local .env — reusing it for the instance."
  ANTHROPIC_API_KEY="$LOCAL_KEY"
else
  warn "No ANTHROPIC_API_KEY in ./.env"
  ask_secret ANTHROPIC_API_KEY "Paste your Anthropic API key:"
fi
[[ -z "$ANTHROPIC_API_KEY" ]] && { warn "a key is required — the chatbot won't boot without it."; exit 1; }
pause "Preflight done. Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Launch the EC2 instance"
say "Opening the EC2 launch wizard. Set it up exactly like this:"
printf '\n'
step "Name:              justin-portfolio"
step "AMI:               Amazon Linux 2023  (x86_64)"
step "Instance type:     t3.micro           (free tier eligible)"
step "Key pair:          Create new → RSA → .pem → download and keep it"
printf '\n'
say "Network settings → Edit → allow all three:"
step "SSH   port 22   — source: My IP     (not anywhere)"
step "HTTP  port 80   — source: Anywhere  (0.0.0.0/0)"
step "HTTPS port 443  — source: Anywhere  (0.0.0.0/0)"
printf '\n'
warn "Port 80 must stay open even though the site is HTTPS-only:"
note "  Let's Encrypt validates over port 80, server-to-server."
printf '\n'
step "Storage: 8 GiB gp3 is plenty."
printf '\n'
warn "Note the region in the top-right of the console."
note "  Everything after this — the Elastic IP especially — must be in the"
note "  SAME region, or it won't be attachable to the instance."
printf '\n'
open_url "https://console.aws.amazon.com/ec2/home#LaunchInstances:"
pause "Launched and showing 'Running'? Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Give it a permanent IP"
say "An instance's default public IP changes every stop/start, which would"
say "silently break the domain later. An Elastic IP is stable and free while"
say "it's attached to a running instance."
printf '\n'
step "Allocate Elastic IP address → Allocate"
step "Select it → Actions → Associate Elastic IP address"
step "Resource type: Instance → choose justin-portfolio → Associate"
printf '\n'
open_url "https://console.aws.amazon.com/ec2/home#Addresses:"
printf '\n'
note "You want the 'Allocated IPv4 address' column — four numbers separated by"
note "dots, e.g. 54.211.8.92. Not the green success banner, not the allocation ID."
printf '\n'
# Loop rather than warn: every later stage ssh's to this value, and a bad one
# surfaces as a baffling SSH failure two stages later rather than here.
while : ; do
  ask ELASTIC_IP "Paste the Elastic IP:"
  ELASTIC_IP="${ELASTIC_IP//[[:space:]]/}"
  if [[ "$ELASTIC_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    bad=0
    IFS='.' read -r o1 o2 o3 o4 <<< "$ELASTIC_IP"
    for o in "$o1" "$o2" "$o3" "$o4"; do (( o > 255 )) && bad=1; done
    (( bad )) || break
    warn "octets must be 0-255 — '$ELASTIC_IP' isn't a valid address."
  else
    warn "that's not an IPv4 address: '$ELASTIC_IP'"
    note "  (if you pasted the success banner or the eipalloc-... ID, look at the"
    note "   'Allocated IPv4 address' column instead)"
  fi
done
write_env ELASTIC_IP "$ELASTIC_IP"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Connect over SSH"
say "Proving you can get in, before we depend on it."
printf '\n'
ask SSH_KEY "Full path to the .pem key you downloaded:"
SSH_KEY="${SSH_KEY/#\~/$HOME}"
[[ -f "$SSH_KEY" ]] || { warn "no file at: $SSH_KEY"; exit 1; }
chmod 400 "$SSH_KEY"
say "Permissions set to 400 (ssh refuses world-readable keys)."
write_env SSH_KEY "$SSH_KEY"

printf '\n'
say "Connecting to $REMOTE_USER@$ELASTIC_IP ..."
until ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 \
          "$REMOTE_USER@$ELASTIC_IP" 'echo CONNECTED' 2>/dev/null | grep -q CONNECTED; do
  printf '\n'
  warn "couldn't connect."
  note "  - instance still booting? give it ~30s after 'Running'"
  note "  - security group SSH rule set to 'My IP', and your IP changed?"
  note "  - Amazon Linux uses user 'ec2-user'"
  confirm "Retry?" || exit 1
done
printf '  %s✓%s SSH works.\n' "$GREEN" "$RESET"
pause "Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Install Docker on the instance"
say "Installing Docker, the Compose plugin, git — and 2GB of swap."
note "t3.micro has 1GB RAM; the image build can spike past that. Swap is"
note "cheap insurance against an OOM-killed build that looks like a hang."
printf '\n'
ssh_run '
  set -e
  sudo dnf install -y docker git >/dev/null
  sudo systemctl enable --now docker
  sudo usermod -aG docker ec2-user
  DCP=/usr/local/lib/docker/cli-plugins
  sudo mkdir -p "$DCP"
  if [ ! -x "$DCP/docker-compose" ]; then
    sudo curl -fsSL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o "$DCP/docker-compose"
    sudo chmod +x "$DCP/docker-compose"
  fi
  if ! sudo swapon --show | grep -q /swapfile; then
    sudo dd if=/dev/zero of=/swapfile bs=1M count=2048 status=none
    sudo chmod 600 /swapfile && sudo mkswap /swapfile >/dev/null && sudo swapon /swapfile
    echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab >/dev/null
  fi
  echo "--- versions ---"
  sudo docker --version
  sudo docker compose version
  free -h | head -3
'
printf '\n'
pause "Docker installed. Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Ship the code and the API key"
say "Cloning from GitHub and writing the instance's own .env."
printf '\n'
note "The key is piped over the SSH session on stdin — never passed as an"
note "argument, so it can't show up in the instance's process list."
printf '\n'

ssh_run "
  set -e
  if [ -d ~/justin-portfolio/.git ]; then
    cd ~/justin-portfolio && git fetch --quiet origin && git reset --hard origin/main --quiet
    echo 'repo updated to origin/main'
  else
    git clone --quiet '$REPO_SSH' ~/justin-portfolio 2>/dev/null \
      || git clone --quiet 'https://github.com/jhatch3/justin-portfolio.git' ~/justin-portfolio
    echo 'repo cloned'
  fi
  cd ~/justin-portfolio && git log --oneline -1
"

printf '%s' "$ANTHROPIC_API_KEY" | ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new \
  "$REMOTE_USER@$ELASTIC_IP" \
  'umask 077 && KEY=$(cat) && printf "ANTHROPIC_API_KEY=%s\n" "$KEY" > ~/justin-portfolio/.env && echo "wrote .env ($(wc -c < ~/justin-portfolio/.env) bytes, mode $(stat -c %a ~/justin-portfolio/.env))"'
printf '  %s✓%s code + secret in place.\n' "$GREEN" "$RESET"
pause "Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Boot over HTTP and test by IP"
warn "This is the stage that saves you an afternoon."
say "The whole .dev TLD is HSTS-preloaded into every browser, so once DNS"
say "points at this box you can NEVER load it over http — the browser"
say "rewrites to https and hard-fails with no click-through."
say "So we prove the app works by raw IP first, while http is still possible."
printf '\n'
ssh_run 'cd ~/justin-portfolio && sudo docker compose up -d --build 2>&1 | tail -15'
printf '\n'
say "Waiting for the app to answer ..."
ok=0
for _ in $(seq 1 30); do
  if curl -fsS --max-time 5 "http://$ELASTIC_IP/api/health" >/dev/null 2>&1; then ok=1; break; fi
  sleep 3
done
printf '\n'
if (( ok )); then
  printf '  %s✓%s health: %s\n' "$GREEN" "$RESET" "$(curl -fsS --max-time 5 "http://$ELASTIC_IP/api/health")"
  for p in "" "desktop" "Resume.pdf"; do
    printf '  %-14s %s\n' "/$p" "$(curl -s -o /dev/null -w '%{http_code}' "http://$ELASTIC_IP/$p")"
  done
  printf '  %-14s %s (expect 404)\n' "/server/grill.mjs" "$(curl -s -o /dev/null -w '%{http_code}' "http://$ELASTIC_IP/server/grill.mjs")"
  open_url "http://$ELASTIC_IP"
  say "Look it over in the browser — this is your last chance to see it over http."
else
  warn "no response from http://$ELASTIC_IP"
  note "  check: ssh in and run  sudo docker compose logs --tail=50"
  note "  also confirm the security group really allows port 80 from anywhere"
  confirm "Continue anyway?" || exit 1
fi
pause "Enter when you're happy with it."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Point GoDaddy at the instance"
say "Two A records, both to $ELASTIC_IP."
printf '\n'
note "Opening your GoDaddy product list — GoDaddy moves its DNS deep-links"
note "around, so navigate from there rather than trusting a bookmark:"
step "Find $DOMAIN → the ⋮ / Manage menu → DNS  (sometimes 'Manage DNS')"
step "EDIT the existing 'A @' record (the GoDaddy parking one) — set it to $ELASTIC_IP"
step "EDIT or add  'A www'                                       — set it to $ELASTIC_IP"
step "Set TTL to 600 seconds on both while we're setting up"
printf '\n'
warn "Do NOT add a second 'A @' record next to the parked one."
note "  Two A records on @ round-robin — half your visitors would land on"
note "  GoDaddy's parking page, intermittently, which is miserable to debug."
printf '\n'
warn "Also check DNS → Forwarding and remove any domain forwarding."
note "  It injects a redirect that fights Caddy."
printf '\n'
open_url "https://dcc.godaddy.com/control/portfolio"
pause "Records saved? Enter to check propagation."

printf '\n'
until [[ "$(dig +short "$DOMAIN" @1.1.1.1 | tail -1)" == "$ELASTIC_IP" ]]; do
  got=$(dig +short "$DOMAIN" @1.1.1.1 | tail -1)
  warn "$DOMAIN currently resolves to: ${got:-(nothing)} — want $ELASTIC_IP"
  note "  propagation is usually <5 min with TTL 600, occasionally longer"
  confirm "Check again?" || { SKIPPED+=("DNS for $DOMAIN not confirmed"); break; }
done
[[ "$(dig +short "$DOMAIN" @1.1.1.1 | tail -1)" == "$ELASTIC_IP" ]] && \
  printf '  %s✓%s %s → %s\n' "$GREEN" "$RESET" "$DOMAIN" "$ELASTIC_IP"
w=$(dig +short "www.$DOMAIN" @1.1.1.1 | tail -1)
[[ "$w" == "$ELASTIC_IP" ]] \
  && printf '  %s✓%s www.%s → %s\n' "$GREEN" "$RESET" "$DOMAIN" "$ELASTIC_IP" \
  || warn "www.$DOMAIN → ${w:-(nothing)} — fix it or www won't redirect"
pause "Enter to continue."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Switch on HTTPS"
say "Swapping to the production stack: Caddy owns 80/443 and the app moves"
say "off the host network entirely. Caddy requests the certificate on boot."
printf '\n'
ssh_run '
  set -e
  cd ~/justin-portfolio
  sudo docker compose down
  sudo docker compose -f docker-compose.prod.yml up -d --build 2>&1 | tail -10
'
printf '\n'
say "Waiting for the certificate ..."
ok=0
for _ in $(seq 1 40); do
  if curl -fsS --max-time 6 "https://$DOMAIN/api/health" >/dev/null 2>&1; then ok=1; break; fi
  sleep 3
done
if (( ok )); then
  printf '  %s✓%s certificate issued, HTTPS live.\n' "$GREEN" "$RESET"
else
  warn "no HTTPS response yet."
  note "  watch it:  ssh -i $SSH_KEY $REMOTE_USER@$ELASTIC_IP 'cd justin-portfolio && sudo docker compose -f docker-compose.prod.yml logs caddy'"
  note "  common causes: port 443 closed in the security group; DNS not"
  note "  actually propagated yet; Let's Encrypt rate limit from retries."
  confirm "Continue to verification anyway?" || exit 1
fi
pause "Enter to run final checks."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Verify the deployment"
printf '\n'
printf '  %shealth%s        %s\n' "$BOLD" "$RESET" "$(curl -fsS --max-time 8 "https://$DOMAIN/api/health" 2>/dev/null || echo 'FAILED')"
printf '  %spages%s\n' "$BOLD" "$RESET"
for p in "" "desktop" "Resume.pdf" "robots.txt" "sitemap.xml"; do
  printf '    %-16s %s\n' "/$p" "$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 "https://$DOMAIN/$p")"
done
printf '  %sinfra must be 404%s\n' "$BOLD" "$RESET"
for p in "server/grill.mjs" "Dockerfile" "README.md" ".env"; do
  printf '    %-16s %s\n' "/$p" "$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 "https://$DOMAIN/$p")"
done
printf '  %swww redirect%s   %s\n' "$BOLD" "$RESET" \
  "$(curl -sI --max-time 8 "https://www.$DOMAIN" 2>/dev/null | grep -i '^location:' | tr -d '\r' || echo '(none)')"
printf '  %ssecurity headers%s\n' "$BOLD" "$RESET"
curl -sI --max-time 8 "https://$DOMAIN" 2>/dev/null \
  | grep -iE 'strict-transport|content-security-policy|x-content-type' \
  | cut -c1-72 | sed 's/^/    /' || note "    (none returned)"
printf '\n'
say "Chatbot end-to-end:"
curl -s --max-time 45 -X POST "https://$DOMAIN/api/chat" \
  -H 'Content-Type: application/json' \
  -d '{"messages":[{"role":"user","content":"In one sentence, where does Justin work?"}]}' \
  2>/dev/null | grep '^data:' | sed 's/^data: //' \
  | jq -r 'select(.type=="delta") | .text' 2>/dev/null | tr -d '\n' | sed 's/^/    /' \
  || note "    (couldn't parse stream — try it in the browser)"
printf '\n\n'
open_url "https://$DOMAIN"

SKIPPED+=("Raise GoDaddy TTL back to 1 hour once you're happy it's stable")
SKIPPED+=("Submit https://$DOMAIN/sitemap.xml in Google Search Console")
SKIPPED+=("Redeploy later with: ssh -i $SSH_KEY $REMOTE_USER@$ELASTIC_IP 'cd justin-portfolio && git pull && sudo docker compose -f docker-compose.prod.yml up -d --build'")

finish
